name: implementing basic pipeline 
on: 
 push: 
 
jobs:
    buildingdockerimageforpython:
         runs-on: ubuntu-latest 
         steps:
            - name: Checkout Repository 
              uses: actions/checkout@v6 
            - name: Build Docker Image 
              run: docker build -t pra-flask-app:v1.0.0 . 
            - name: Run Container 
              run: docker run -d -p 5000:5000 --name pra-flask-container pra-flask-app:v1.0.0 
            - name: Smoke Test 
              run: | 
                 sleep 5   
                 curl http://localhost:5000/health